#!/usr/bin/env python3
"""Generates bit-exact NumPy reference values for numpy4j parity validation.

Outputs a .properties file with hex-encoded float32 IEEE 754 values.
Run: python3 tools/generate_numpy_reference.py > tools/numpy_reference.properties
"""
import numpy as np
import struct
import sys

def to_hex(arr):
    """Convert float32 array to comma-separated hex strings (big-endian int bits)."""
    flat = np.asarray(arr, dtype=np.float32).flatten()
    return ",".join(f"{struct.unpack('>I', struct.pack('>f', float(v)))[0]:08x}" for v in flat)

def main():
    print("# NumPy reference values for bit-exact parity validation")
    print(f"# Generated by: python3 tools/generate_numpy_reference.py")
    print(f"# NumPy version: {np.__version__}")
    print(f"# Platform: {sys.platform}")
    cfg = np.show_config(mode='dicts')
    blas_name = cfg.get('Build Dependencies', {}).get('blas', {}).get('name', 'unknown')
    print(f"# BLAS: {blas_name}")
    print()

    # ── exp ──
    exp_in = np.array([0.5, 1.0, 2.0, -1.0, 10.0, -10.0, 0.001, 88.0, -87.0], dtype=np.float32)
    print(f"exp.input={to_hex(exp_in)}")
    print(f"exp.output={to_hex(np.exp(exp_in))}")

    # ── softmax ──
    sm_in = np.array([[1, 2, 3, 4], [1, 1, 1, 1], [0, 0, 0, 0]], dtype=np.float32)
    e = np.exp(sm_in - np.max(sm_in, axis=-1, keepdims=True))
    sm_out = e / np.sum(e, axis=-1, keepdims=True)
    print(f"softmax.input={to_hex(sm_in)}")
    print(f"softmax.shape=3,4")
    print(f"softmax.output={to_hex(sm_out)}")

    # ── solve (small, scalar path) ──
    A_s = np.array([[4, 1], [1, 3]], dtype=np.float32)
    b_s = np.array([1, 2], dtype=np.float32)
    print(f"solve_2x2.A={to_hex(A_s)}")
    print(f"solve_2x2.b={to_hex(b_s)}")
    print(f"solve_2x2.x={to_hex(np.linalg.solve(A_s, b_s))}")

    # ── solve (8x8, LAPACK path) ──
    A8 = np.zeros((8, 8), dtype=np.float32)
    for i in range(8):
        A8[i, i] = 9
        if i > 0: A8[i, i-1] = 1
        if i < 7: A8[i, i+1] = 1
    b8 = np.array([1, 0, 0, 0, 0, 0, 0, 1], dtype=np.float32)
    print(f"solve_8x8.A={to_hex(A8)}")
    print(f"solve_8x8.b={to_hex(b8)}")
    print(f"solve_8x8.x={to_hex(np.linalg.solve(A8, b8))}")

    # ── inv (small) ──
    A_inv = np.array([[1, 2], [3, 4]], dtype=np.float32)
    print(f"inv_2x2.A={to_hex(A_inv)}")
    print(f"inv_2x2.result={to_hex(np.linalg.inv(A_inv))}")

    # ── inv (8x8) ──
    print(f"inv_8x8.A={to_hex(A8)}")
    print(f"inv_8x8.result={to_hex(np.linalg.inv(A8))}")

    # ── cholesky ──
    A_ch = np.array([[4, 2], [2, 3]], dtype=np.float32)
    print(f"cholesky_2x2.A={to_hex(A_ch)}")
    print(f"cholesky_2x2.L={to_hex(np.linalg.cholesky(A_ch))}")

    A_ch8 = (A8.T @ A8 + np.eye(8, dtype=np.float32) * 8).astype(np.float32)
    print(f"cholesky_8x8.A={to_hex(A_ch8)}")
    print(f"cholesky_8x8.L={to_hex(np.linalg.cholesky(A_ch8))}")

    # ── det ──
    print(f"det_2x2.A={to_hex(A_inv)}")
    print(f"det_2x2.result={to_hex(np.float32(np.linalg.det(A_inv)))}")
    print(f"det_8x8.A={to_hex(A8)}")
    print(f"det_8x8.result={to_hex(np.float32(np.linalg.det(A8)))}")

    # ── svd ──
    A_svd = np.array([[1, 2], [3, 4], [5, 6]], dtype=np.float32)
    U, S, Vt = np.linalg.svd(A_svd, full_matrices=False)
    print(f"svd_3x2.A={to_hex(A_svd)}")
    print(f"svd_3x2.S={to_hex(S)}")
    print(f"svd_3x2.U={to_hex(U)}")
    print(f"svd_3x2.Vt={to_hex(Vt)}")

    # ── eigvalsh ──
    A_eig = np.array([[2, 1], [1, 3]], dtype=np.float32)
    w = np.linalg.eigvalsh(A_eig)
    print(f"eigvalsh_2x2.A={to_hex(A_eig)}")
    print(f"eigvalsh_2x2.w={to_hex(w)}")

    A_eig8 = (A8 + A8.T) / 2  # ensure symmetric
    w8 = np.linalg.eigvalsh(A_eig8.astype(np.float32))
    print(f"eigvalsh_8x8.A={to_hex(A_eig8.astype(np.float32))}")
    print(f"eigvalsh_8x8.w={to_hex(w8)}")

if __name__ == "__main__":
    main()
