///usr/bin/env java --enable-preview --source 26 --class-path target/classes "$0" "$@"; exit $?
/**
 * Bit-exact parity validation against NumPy reference values.
 * Reads tools/numpy_reference.properties (generated by generate_numpy_reference.py)
 * and compares every output bit-for-bit.
 *
 * Usage: mvn compile && java --enable-preview --source 26 --class-path target/classes \
 *        tools/ValidateNumpyParity.java
 */
import com.sparrowlogic.numpy4j.*;
import java.io.*;
import java.lang.foreign.Arena;
import java.util.*;

public class ValidateNumpyParity {
    static Properties props = new Properties();
    static int totalTests = 0;
    static int passed = 0;
    static int failed = 0;

    public static void main(String[] args) throws Exception {
        props.load(new FileReader("tools/numpy_reference.properties"));
        System.out.println("=== NumPy Bit-Exact Parity Validation ===\n");

        try (var a = Arena.ofConfined()) {
            testExp(a);
            testSoftmax(a);
            testSolve2x2(a);
            testSolve8x8(a);
            testInv2x2(a);
            testInv8x8(a);
            testCholesky2x2(a);
            testCholesky8x8(a);
            testDet2x2(a);
            testDet8x8(a);
            testSvd(a);
            testEigvalsh2x2(a);
            testEigvalsh8x8(a);
        }

        System.out.printf("%n=== RESULTS: %d/%d passed", passed, totalTests);
        if (failed > 0) System.out.printf(", %d FAILED", failed);
        System.out.println(failed == 0 ? " ✅ ===" : " ⚠️  ===");
        System.exit(failed > 0 ? 1 : 0);
    }

    static void testExp(Arena a) {
        var input = arr(a, "exp.input");
        check("exp", Ufunc.exp(input).toFloatArray(), ref("exp.output"));
    }

    static void testSoftmax(Arena a) {
        var input = arr(a, "softmax.input", 3, 4);
        check("softmax", ML.softmax(input).toFloatArray(), ref("softmax.output"));
    }

    static void testSolve2x2(Arena a) {
        check("solve_2x2", LinAlg.solve(arr(a, "solve_2x2.A", 2, 2),
                arr(a, "solve_2x2.b")).toFloatArray(), ref("solve_2x2.x"));
    }

    static void testSolve8x8(Arena a) {
        check("solve_8x8", LinAlg.solve(arr(a, "solve_8x8.A", 8, 8),
                arr(a, "solve_8x8.b")).toFloatArray(), ref("solve_8x8.x"));
    }

    static void testInv2x2(Arena a) {
        check("inv_2x2", LinAlg.inv(arr(a, "inv_2x2.A", 2, 2)).toFloatArray(),
                ref("inv_2x2.result"));
    }

    static void testInv8x8(Arena a) {
        check("inv_8x8", LinAlg.inv(arr(a, "inv_8x8.A", 8, 8)).toFloatArray(),
                ref("inv_8x8.result"));
    }

    static void testCholesky2x2(Arena a) {
        check("chol_2x2", LinAlg.cholesky(arr(a, "cholesky_2x2.A", 2, 2)).toFloatArray(),
                ref("cholesky_2x2.L"));
    }

    static void testCholesky8x8(Arena a) {
        check("chol_8x8", LinAlg.cholesky(arr(a, "cholesky_8x8.A", 8, 8)).toFloatArray(),
                ref("cholesky_8x8.L"));
    }

    static void testDet2x2(Arena a) {
        float got = LinAlg.det(arr(a, "det_2x2.A", 2, 2));
        float[] expected = ref("det_2x2.result");
        check("det_2x2", new float[]{got}, expected);
    }

    static void testDet8x8(Arena a) {
        float got = LinAlg.det(arr(a, "det_8x8.A", 8, 8));
        float[] expected = ref("det_8x8.result");
        check("det_8x8", new float[]{got}, expected);
    }

    static void testSvd(Arena a) {
        NdArray[] usv = LinAlg.svd(arr(a, "svd_3x2.A", 3, 2));
        check("svd_S", usv[1].toFloatArray(), ref("svd_3x2.S"));
        // SVD singular vectors have arbitrary sign — compare |values|
        checkAbs("svd_U", usv[0].toFloatArray(), ref("svd_3x2.U"));
        checkAbs("svd_Vt", usv[2].toFloatArray(), ref("svd_3x2.Vt"));
    }

    static void testEigvalsh2x2(Arena a) {
        NdArray[] result = LinAlg.eigh(arr(a, "eigvalsh_2x2.A", 2, 2));
        check("eigh_2x2", result[0].toFloatArray(), ref("eigvalsh_2x2.w"));
    }

    static void testEigvalsh8x8(Arena a) {
        NdArray[] result = LinAlg.eigh(arr(a, "eigvalsh_8x8.A", 8, 8));
        check("eigh_8x8", result[0].toFloatArray(), ref("eigvalsh_8x8.w"));
    }

    // ── Helpers ──

    static void check(String name, float[] got, float[] expected) {
        totalTests++;
        int n = expected.length;
        int exact = 0;
        List<String> diffs = new ArrayList<>();
        for (int i = 0; i < n; i++) {
            int gotBits = Float.floatToRawIntBits(got[i]);
            int expBits = Float.floatToRawIntBits(expected[i]);
            if (gotBits == expBits) {
                exact++;
            } else {
                diffs.add(String.format("    [%d] got=%08x exp=%08x (%.8f vs %.8f) %d ULPs",
                        i, gotBits, expBits, got[i], expected[i], Math.abs(gotBits - expBits)));
            }
        }
        reportResult(name, exact, n, diffs);
    }

    static void checkAbs(String name, float[] got, float[] expected) {
        totalTests++;
        int n = expected.length;
        int exact = 0;
        List<String> diffs = new ArrayList<>();
        for (int i = 0; i < n; i++) {
            int gotBits = Float.floatToRawIntBits(Math.abs(got[i]));
            int expBits = Float.floatToRawIntBits(Math.abs(expected[i]));
            if (gotBits == expBits) {
                exact++;
            } else {
                diffs.add(String.format("    [%d] |got|=%08x |exp|=%08x (%.8f vs %.8f) %d ULPs",
                        i, gotBits, expBits, Math.abs(got[i]), Math.abs(expected[i]),
                        Math.abs(gotBits - expBits)));
            }
        }
        reportResult(name, exact, n, diffs);
    }

    static void reportResult(String name, int exact, int n, List<String> diffs) {
        if (exact == n) {
            System.out.printf("  %-12s BIT-EXACT ✅  (%d values)%n", name, n);
            passed++;
        } else {
            System.out.printf("  %-12s FAILED ❌  (%d/%d exact)%n", name, exact, n);
            for (String d : diffs) System.out.println(d);
            failed++;
        }
    }

    static float[] ref(String key) {
        return hexToFloats(props.getProperty(key));
    }

    static NdArray arr(Arena a, String key, int... shape) {
        float[] data = hexToFloats(props.getProperty(key));
        return shape.length > 0
                ? NdArrayFactory.array(a, data, shape)
                : NdArrayFactory.array(a, data);
    }

    static float[] hexToFloats(String hex) {
        String[] parts = hex.split(",");
        float[] result = new float[parts.length];
        for (int i = 0; i < parts.length; i++) {
            result[i] = Float.intBitsToFloat(Integer.parseUnsignedInt(parts[i].trim(), 16));
        }
        return result;
    }
}
