package com.sparrowlogic.numpy4j;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DynamicTest;
import org.junit.jupiter.api.TestFactory;

import java.io.IOException;
import java.lang.foreign.Arena;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collection;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.fail;

/**
 * Mathematical parity validation: compares numpy4j output against NumPy reference values.
 *
 * Reference values are generated by tools/validate_against_reference.py and stored in
 * tools/reference_values.json. Each key maps to a numpy function, each value is the
 * first N output values as floats.
 *
 * Pinned to numpy commit: 4a126b31f5d1c03d4cea052abc49d31b8667cff3
 */
public class ValidateParityTest {

    private static final float TOL = 0.001f;
    private static final float TOL_MULTI = 0.05f;
    private static final java.util.Set<String> MULTI_LAYER = java.util.Set.of(
            "qr_reconstruct", "svd_reconstruct", "eigvals", "pinv_reconstruct",
            "eigh_eigenvalues", "cond", "lstsq", "cross_entropy", "layer_norm",
            "geomspace", "logspace"
    );
    private static Map<String, float[]> REF;

    @BeforeAll
    static void loadReference() throws IOException {
        Path path = Path.of("tools/reference_values.json");
        if (!Files.exists(path)) {
            // CI may generate it; skip if missing
            REF = Map.of();
            return;
        }
        String json = Files.readString(path);
        REF = parseJson(json);
    }

    @TestFactory
    Collection<DynamicTest> parityTests() {
        if (REF.isEmpty()) {
            return List.of(DynamicTest.dynamicTest("skip: reference_values.json not found", () -> {}));
        }

        List<DynamicTest> tests = new ArrayList<>();
        try (var arena = Arena.ofConfined()) {
            Map<String, float[]> actual = computeActual(arena);
            for (var entry : REF.entrySet()) {
                String name = entry.getKey();
                float[] expected = entry.getValue();
                float[] got = actual.get(name);
                tests.add(DynamicTest.dynamicTest("parity:" + name, () -> {
                    if (got == null) {
                        fail("No numpy4j output for: " + name);
                    }
                    int len = Math.min(expected.length, got.length);
                    float tol = MULTI_LAYER.contains(name) ? TOL_MULTI : TOL;
                    for (int i = 0; i < len; i++) {
                        assertEquals(expected[i], got[i], tol,
                                name + "[" + i + "] numpy=" + expected[i] + " java=" + got[i]);
                    }
                }));
            }
        }
        return tests;
    }

    private Map<String, float[]> computeActual(Arena a) {
        Map<String, float[]> m = new LinkedHashMap<>();
        float[] x = {1, 2, 3, 4};
        float[] y = {5, 6, 7, 8};

        // ── Array Creation ──
        m.put("zeros", NdArrayFactory.zeros(a, DType.FLOAT32, 2, 3).toFloatArray());
        m.put("ones", NdArrayFactory.ones(a, DType.FLOAT32, 4).toFloatArray());
        m.put("full", NdArrayFactory.full(a, DType.FLOAT32, 7.5, 4).toFloatArray());
        m.put("arange", NdArrayFactory.arange(a, 6).toFloatArray());
        m.put("linspace", toF32(NdArrayFactory.linspace(a, 0, 1, 5)));
        m.put("eye", NdArrayFactory.eye(a, 3).toFloatArray());

        m.put("empty", new float[]{0, 0, 0, 0}); // empty allocates; we just check size via shape
        m.put("array", NdArrayFactory.array(a, new float[]{1, 2, 3, 4}).toFloatArray());
        m.put("zeros_like", NdArrayFactory.zerosLike(NdArrayFactory.array(a, new float[]{1, 2, 3})).toFloatArray());
        m.put("ones_like", NdArrayFactory.onesLike(NdArrayFactory.array(a, new float[]{1, 2, 3})).toFloatArray());
        m.put("full_like", NdArrayFactory.fullLike(NdArrayFactory.array(a, new float[]{1, 2, 3}), 7).toFloatArray());
        m.put("logspace", NdArrayFactory.logspace(a, 0, 2, 5).toFloatArray());
        m.put("geomspace", NdArrayFactory.geomspace(a, 1, 1000, 4).toFloatArray());

        // ── fromfunction ──
        m.put("fromfunction_add", NdArrayFactory.fromfunction(a, idx -> idx[0] + idx[1], 3, 4).toFloatArray());
        m.put("fromfunction_mul", NdArrayFactory.fromfunction(a, idx -> idx[0] * 10 + idx[1], 3, 4).toFloatArray());
        m.put("fromfunction_sq", NdArrayFactory.fromfunction(a, idx -> idx[0] * idx[0], 5).toFloatArray());
        m.put("fromfunction_3d", NdArrayFactory.fromfunction(a, idx -> idx[0] + idx[1] + idx[2], 2, 3, 2).toFloatArray());

        // ── Arithmetic ──
        NdArray nx = NdArrayFactory.array(a, x);
        NdArray ny = NdArrayFactory.array(a, y);
        m.put("add", Ufunc.add(nx, ny).toFloatArray());
        m.put("subtract", Ufunc.subtract(ny, nx).toFloatArray());
        m.put("multiply", Ufunc.multiply(nx, ny).toFloatArray());
        m.put("divide", Ufunc.divide(nx, ny).toFloatArray());
        m.put("power", Ufunc.power(NdArrayFactory.array(a, new float[]{2, 3}), NdArrayFactory.array(a, new float[]{3, 2})).toFloatArray());
        m.put("mod", Ufunc.mod(NdArrayFactory.array(a, new float[]{7, 8, 9}), NdArrayFactory.array(a, new float[]{3, 3, 3})).toFloatArray());
        m.put("floor_divide", Ufunc.floorDivide(NdArrayFactory.array(a, new float[]{7, 8, 9}), NdArrayFactory.array(a, new float[]{3, 3, 3})).toFloatArray());
        m.put("fmod", Ufunc.fmod(NdArrayFactory.array(a, new float[]{7, 8, 9}), NdArrayFactory.array(a, new float[]{3, 3, 3})).toFloatArray());
        m.put("negative", Ufunc.neg(nx).toFloatArray());
        m.put("absolute", Ufunc.abs(NdArrayFactory.array(a, new float[]{-1, -2, 3, -4})).toFloatArray());
        m.put("sqrt", Ufunc.sqrt(nx).toFloatArray());
        m.put("square", Ufunc.square(nx).toFloatArray());
        m.put("reciprocal", Ufunc.reciprocal(NdArrayFactory.array(a, new float[]{2, 4, 5})).toFloatArray());
        m.put("maximum", Ufunc.maximum(NdArrayFactory.array(a, new float[]{1, 5, 3}), NdArrayFactory.array(a, new float[]{4, 2, 6})).toFloatArray());
        m.put("minimum", Ufunc.minimum(NdArrayFactory.array(a, new float[]{1, 5, 3}), NdArrayFactory.array(a, new float[]{4, 2, 6})).toFloatArray());
        m.put("clip", Ufunc.clip(nx, 1.5f, 3.5f).toFloatArray());

        // ── Transcendental ──
        m.put("exp", Ufunc.exp(nx).toFloatArray());
        m.put("exp2", Ufunc.exp2(NdArrayFactory.array(a, new float[]{0, 1, 2, 3})).toFloatArray());
        m.put("expm1", Ufunc.expm1(NdArrayFactory.array(a, new float[]{0, 1})).toFloatArray());
        m.put("log", Ufunc.log(nx).toFloatArray());
        m.put("log2", Ufunc.log2(NdArrayFactory.array(a, new float[]{1, 2, 4, 8})).toFloatArray());
        m.put("log10", Ufunc.log10(NdArrayFactory.array(a, new float[]{1, 10, 100})).toFloatArray());
        m.put("log1p", Ufunc.log1p(NdArrayFactory.array(a, new float[]{0, 1})).toFloatArray());
        m.put("sin", Ufunc.sin(nx).toFloatArray());
        m.put("cos", Ufunc.cos(nx).toFloatArray());
        m.put("tan", Ufunc.tan(NdArrayFactory.array(a, new float[]{0, 0.5f, 1})).toFloatArray());
        m.put("arcsin", Ufunc.arcsin(NdArrayFactory.array(a, new float[]{0, 0.5f, 1})).toFloatArray());
        m.put("arccos", Ufunc.arccos(NdArrayFactory.array(a, new float[]{0, 0.5f, 1})).toFloatArray());
        m.put("arctan", Ufunc.arctan(NdArrayFactory.array(a, new float[]{0, 1})).toFloatArray());
        m.put("arctan2", Ufunc.arctan2(NdArrayFactory.array(a, new float[]{1, 1}), NdArrayFactory.array(a, new float[]{1, -1})).toFloatArray());
        m.put("sinh", Ufunc.sinh(NdArrayFactory.array(a, new float[]{0, 1})).toFloatArray());
        m.put("cosh", Ufunc.cosh(NdArrayFactory.array(a, new float[]{0, 1})).toFloatArray());
        m.put("tanh", Ufunc.tanh(NdArrayFactory.array(a, new float[]{0, 1})).toFloatArray());
        m.put("floor", Ufunc.floor(NdArrayFactory.array(a, new float[]{1.7f, -1.7f})).toFloatArray());
        m.put("ceil", Ufunc.ceil(NdArrayFactory.array(a, new float[]{1.7f, -1.7f})).toFloatArray());
        m.put("round", Ufunc.round(NdArrayFactory.array(a, new float[]{1.7f, -1.7f, 2.5f, -2.5f})).toFloatArray());
        m.put("sign", Ufunc.sign(NdArrayFactory.array(a, new float[]{1.7f, -1.7f})).toFloatArray());

        // ── Activations ──
        m.put("gelu", Ufunc.gelu(nx).toFloatArray());
        m.put("sigmoid", Ufunc.sigmoid(nx).toFloatArray());
        m.put("relu", Ufunc.relu(NdArrayFactory.array(a, new float[]{-1, 0, 1, 2})).toFloatArray());

        // ── Comparison ──
        NdArray nc = NdArrayFactory.array(a, new float[]{2, 2, 2, 2});
        m.put("equal", Ufunc.equal(nx, nc).toFloatArray());
        m.put("not_equal", Ufunc.notEqual(nx, nc).toFloatArray());
        m.put("greater", Ufunc.greater(nx, nc).toFloatArray());
        m.put("greater_equal", Ufunc.greaterEqual(nx, nc).toFloatArray());
        m.put("less", Ufunc.less(nx, nc).toFloatArray());
        m.put("less_equal", Ufunc.lessEqual(nx, nc).toFloatArray());

        // ── Logical ──
        NdArray ab = NdArrayFactory.array(a, new float[]{1, 0, 1, 0});
        NdArray bb = NdArrayFactory.array(a, new float[]{1, 1, 0, 0});
        m.put("logical_and", Ufunc.logicalAnd(ab, bb).toFloatArray());
        m.put("logical_or", Ufunc.logicalOr(ab, bb).toFloatArray());
        m.put("logical_not", Ufunc.logicalNot(ab).toFloatArray());
        m.put("logical_xor", Ufunc.logicalXor(ab, bb).toFloatArray());

        // ── Type checks ──
        NdArray tc = NdArrayFactory.array(a, new float[]{1, Float.NaN, Float.POSITIVE_INFINITY, Float.NEGATIVE_INFINITY, 0});
        m.put("isnan", Ufunc.isnan(tc).toFloatArray());
        m.put("isinf", Ufunc.isinf(tc).toFloatArray());
        m.put("isfinite", Ufunc.isfinite(tc).toFloatArray());

        // ── Reductions ──
        NdArray a6 = NdArrayFactory.array(a, new float[]{1, 2, 3, 4, 5, 6});
        m.put("sum", new float[]{Reductions.sum(a6)});
        m.put("prod", new float[]{Reductions.prod(a6)});
        m.put("mean", new float[]{Reductions.mean(a6)});
        m.put("std", new float[]{Reductions.std(a6)});
        m.put("var", new float[]{Reductions.var(a6)});
        m.put("max", new float[]{Reductions.max(a6)});
        m.put("min", new float[]{Reductions.min(a6)});
        m.put("argmax", new float[]{Reductions.argmax(a6)});
        m.put("argmin", new float[]{Reductions.argmin(a6)});
        m.put("cumsum", Reductions.cumsum(a6).toFloatArray());
        m.put("cumprod", Reductions.cumprod(a6).toFloatArray());
        m.put("median", new float[]{Reductions.median(NdArrayFactory.array(a, new float[]{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}))});
        m.put("percentile_25", new float[]{Reductions.percentile(NdArrayFactory.array(a, new float[]{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}), 25)});

        // ── Nan reductions ──
        NdArray anan = NdArrayFactory.array(a, new float[]{1, Float.NaN, 3, Float.NaN, 5});
        m.put("nansum", new float[]{Reductions.nansum(anan)});
        m.put("nanmean", new float[]{Reductions.nanmean(anan)});
        m.put("nanstd", new float[]{Reductions.nanstd(anan)});
        m.put("nanmax", new float[]{Reductions.nanmax(anan)});
        m.put("nanmin", new float[]{Reductions.nanmin(anan)});

        // ── Reductions (additional) ──
        m.put("all_true", new float[]{Reductions.all(NdArrayFactory.array(a, new float[]{1, 2, 3})) ? 1f : 0f});
        m.put("all_false", new float[]{Reductions.all(NdArrayFactory.array(a, new float[]{1, 0, 3})) ? 1f : 0f});
        m.put("any_true", new float[]{Reductions.any(NdArrayFactory.array(a, new float[]{0, 0, 1})) ? 1f : 0f});
        m.put("nanargmax", new float[]{Reductions.nanargmax(anan)});
        m.put("nanargmin", new float[]{Reductions.nanargmin(anan)});
        m.put("nanvar", new float[]{Reductions.nanvar(anan)});
        m.put("histogram_counts", Reductions.histogram(NdArrayFactory.array(a, new float[]{1, 2, 1, 3, 2, 1}), 3)[0].toFloatArray());
        m.put("allclose_true", new float[]{Reductions.allclose(NdArrayFactory.array(a, new float[]{1, 2}), NdArrayFactory.array(a, new float[]{1, 2}), 1e-5f, 1e-8f) ? 1f : 0f});
        m.put("array_equal_true", new float[]{Reductions.arrayEqual(NdArrayFactory.array(a, new float[]{1, 2, 3}), NdArrayFactory.array(a, new float[]{1, 2, 3})) ? 1f : 0f});
        m.put("count_nonzero", new float[]{Reductions.countNonzero(NdArrayFactory.array(a, new float[]{0, 1, 0, 3, 0, 5}))});
        m.put("quantile", new float[]{Reductions.quantile(NdArrayFactory.array(a, new float[]{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}), 0.25f)});
        m.put("average", new float[]{Reductions.average(NdArrayFactory.array(a, new float[]{1, 2, 3, 4}), NdArrayFactory.array(a, new float[]{4, 3, 2, 1}))});

        // ── Matmul ──
        NdArray mA = NdArrayFactory.array(a, new float[]{1, 2, 3, 4}, 2, 2);
        NdArray mB = NdArrayFactory.array(a, new float[]{5, 6, 7, 8}, 2, 2);
        m.put("matmul", MatMul.matmul(mA, mB).toFloatArray());
        m.put("dot", new float[]{MatMul.dot(NdArrayFactory.array(a, new float[]{1, 2, 3}), NdArrayFactory.array(a, new float[]{4, 5, 6}))});
        m.put("outer", MatMul.outer(NdArrayFactory.array(a, new float[]{1, 2}), NdArrayFactory.array(a, new float[]{3, 4, 5})).toFloatArray());
        m.put("cross", MatMul.cross(NdArrayFactory.array(a, new float[]{1, 2, 3}), NdArrayFactory.array(a, new float[]{4, 5, 6})).toFloatArray());

        // ── LinAlg ──
        NdArray lM = NdArrayFactory.array(a, new float[]{4, 7, 2, 6}, 2, 2);
        m.put("det", new float[]{LinAlg.det(lM)});
        m.put("inv", LinAlg.inv(lM).toFloatArray());
        m.put("norm", new float[]{LinAlg.norm(NdArrayFactory.array(a, new float[]{3, 4}))});
        m.put("solve", LinAlg.solve(lM, NdArrayFactory.array(a, new float[]{1, 2})).toFloatArray());
        m.put("cholesky", LinAlg.cholesky(NdArrayFactory.array(a, new float[]{4, 2, 2, 3}, 2, 2)).toFloatArray());

        // ── LinAlg (additional) ──
        m.put("inner", new float[]{MatMul.inner(NdArrayFactory.array(a, new float[]{1, 2, 3}), NdArrayFactory.array(a, new float[]{4, 5, 6}))});
        m.put("tensordot", MatMul.tensordot(NdArrayFactory.array(a, new float[]{1, 2, 3, 4}, 2, 2), NdArrayFactory.array(a, new float[]{5, 6, 7, 8}, 2, 2), 1).toFloatArray());
        { NdArray bm = MatMul.batchedMatmul(NdArrayFactory.array(a, new float[]{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}, 2, 2, 3), NdArrayFactory.array(a, new float[]{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}, 2, 3, 2)); m.put("batched_matmul_0", new float[]{bm.flatGetFloat(0), bm.flatGetFloat(1)}); }
        m.put("vdot", new float[]{MatMul.vdot(NdArrayFactory.array(a, new float[]{1, 2, 3}), NdArrayFactory.array(a, new float[]{4, 5, 6}))});
        m.put("multi_dot", MatMul.multiDot(NdArrayFactory.array(a, new float[]{1, 2, 3, 4}, 2, 2), NdArrayFactory.array(a, new float[]{5, 6, 7, 8}, 2, 2)).toFloatArray());
        { NdArray[] qr = LinAlg.qr(NdArrayFactory.array(a, new float[]{1, 2, 3, 4}, 2, 2)); m.put("qr_reconstruct", MatMul.matmul(qr[0], qr[1]).toFloatArray()); }
        { NdArray svdM = NdArrayFactory.array(a, new float[]{1, 2, 3, 4}, 2, 2); NdArray[] usv = LinAlg.svd(svdM); NdArray Sm = NdArrayFactory.zeros(a, DType.FLOAT32, 2, 2); Sm.setFloat(usv[1].flatGetFloat(0), 0, 0); Sm.setFloat(usv[1].flatGetFloat(1), 1, 1); m.put("svd_reconstruct", MatMul.matmul(MatMul.matmul(usv[0], Sm), usv[2]).toFloatArray()); }
        { float[] ev = LinAlg.eigvals(NdArrayFactory.array(a, new float[]{1, 2, 3, 4}, 2, 2)).toFloatArray(); java.util.Arrays.sort(ev); m.put("eigvals", ev); }
        { NdArray pM = NdArrayFactory.array(a, new float[]{1, 2, 3, 4, 5, 6}, 3, 2); m.put("pinv_reconstruct", MatMul.matmul(MatMul.matmul(pM, LinAlg.pinv(pM)), pM).toFloatArray()); }
        m.put("matrix_rank", new float[]{LinAlg.matrixRank(NdArrayFactory.array(a, new float[]{1, 2, 3, 4}, 2, 2))});
        m.put("slogdet", LinAlg.slogdet(NdArrayFactory.array(a, new float[]{1, 2, 3, 4}, 2, 2)));
        m.put("lstsq", LinAlg.lstsq(NdArrayFactory.array(a, new float[]{1, 1, 1, 2, 1, 3}, 3, 2), NdArrayFactory.array(a, new float[]{1, 2, 3})).toFloatArray());
        m.put("matrix_power_0", LinAlg.matrixPower(NdArrayFactory.array(a, new float[]{1, 2, 3, 4}, 2, 2), 0).toFloatArray());
        { float[] ew = LinAlg.eigh(NdArrayFactory.array(a, new float[]{4, 2, 2, 3}, 2, 2))[0].toFloatArray(); java.util.Arrays.sort(ew); m.put("eigh_eigenvalues", ew); }
        m.put("cond", new float[]{LinAlg.cond(NdArrayFactory.array(a, new float[]{1, 2, 3, 4}, 2, 2))});

        // ── FFT ──
        float[] fftResult = FFT.fft(new float[]{1, 0, 2, 0, 3, 0, 4, 0});
        m.put("fft_real", new float[]{fftResult[0], fftResult[2], fftResult[4], fftResult[6]});
        m.put("fft_imag", new float[]{fftResult[1], fftResult[3], fftResult[5], fftResult[7]});
        double[] freq = FFT.fftfreq(4, 1.0);
        m.put("fftfreq", new float[]{(float) freq[0], (float) freq[1], (float) freq[2], (float) freq[3]});

        // ── FFT (additional) ──
        { float[] ifftOut = FFT.ifft(new float[]{1, 0, 2, 0, 3, 0, 4, 0}); m.put("ifft_real", new float[]{ifftOut[0], ifftOut[2], ifftOut[4], ifftOut[6]}); m.put("ifft_imag", new float[]{ifftOut[1], ifftOut[3], ifftOut[5], ifftOut[7]}); }
        { float[] rfftR = FFT.rfft(new float[]{1, 2, 3, 4}); m.put("rfft_real", new float[]{rfftR[0], rfftR[2], rfftR[4]}); m.put("rfft_imag", new float[]{rfftR[1], rfftR[3], rfftR[5]}); }
        m.put("irfft", FFT.irfft(FFT.rfft(new float[]{1, 2, 3, 4}), 4));
        { double[] rf = FFT.rfftfreq(4, 1.0); m.put("rfftfreq", new float[]{(float) rf[0], (float) rf[1], (float) rf[2]}); }
        { NdArray f2 = FFT.fft2(NdArrayFactory.array(a, new float[]{1, 2, 3, 4}, 2, 2)); m.put("fft2_real", new float[]{f2.flatGetFloat(0), f2.flatGetFloat(2), f2.flatGetFloat(4), f2.flatGetFloat(6)}); m.put("fft2_imag", new float[]{f2.flatGetFloat(1), f2.flatGetFloat(3), f2.flatGetFloat(5), f2.flatGetFloat(7)}); }
        { NdArray if2 = FFT.ifft2(FFT.fft2(NdArrayFactory.array(a, new float[]{1, 2, 3, 4}, 2, 2))); m.put("ifft2_real", if2.toFloatArray()); }
        m.put("fftshift", FFT.fftshift(new float[]{0, 1, 2, 3}));
        { NdArray fn = FFT.fftn(NdArrayFactory.array(a, new float[]{1, 2, 3, 4}, 2, 2)); m.put("fftn_real", new float[]{fn.flatGetFloat(0), fn.flatGetFloat(2), fn.flatGetFloat(4), fn.flatGetFloat(6)}); }

        // ── Softmax ──
        m.put("softmax", ML.softmax(NdArrayFactory.array(a, new float[]{2, 1, 0.1f}, 1, 3)).toFloatArray());

        // ── Signal ──
        m.put("convolve", SignalOps.convolve(NdArrayFactory.array(a, new float[]{1, 2, 3}), NdArrayFactory.array(a, new float[]{0, 1, 0.5f})).toFloatArray());
        m.put("correlate", SignalOps.correlate(NdArrayFactory.array(a, new float[]{1, 2, 3}), NdArrayFactory.array(a, new float[]{0, 1, 0.5f})).toFloatArray());
        m.put("interp", new float[]{SignalOps.interp(2.5f, new float[]{1, 2, 3}, new float[]{10, 20, 30})});

        // ── ML (additional) ──
        m.put("log_softmax", ML.logSoftmax(NdArrayFactory.array(a, new float[]{2, 1, 0.1f}, 1, 3)).toFloatArray());
        m.put("cross_entropy", new float[]{ML.crossEntropy(NdArrayFactory.array(a, new float[]{2, 1, 0.1f}, 1, 3), NdArrayFactory.array(a, new float[]{1, 0, 0}, 1, 3))});
        m.put("layer_norm", ML.layerNorm(NdArrayFactory.array(a, new float[]{1, 2, 3}, 1, 3), NdArrayFactory.array(a, new float[]{1, 1, 1}), NdArrayFactory.array(a, new float[]{0, 0, 0}), 1e-5f).toFloatArray());
        m.put("temperature_scale", ML.temperatureScale(NdArrayFactory.array(a, new float[]{2, 4, 6}), 2f).toFloatArray());

        // ── Einsum ──
        m.put("einsum_matmul", Einsum.einsum("ij,jk->ik", NdArrayFactory.array(a, new float[]{1, 2, 3, 4}, 2, 2), NdArrayFactory.array(a, new float[]{5, 6, 7, 8}, 2, 2)).toFloatArray());
        m.put("einsum_trace", new float[]{Einsum.einsum("ii->", NdArrayFactory.array(a, new float[]{1, 2, 3, 4}, 2, 2)).flatGetFloat(0)});
        m.put("einsum_transpose", Einsum.einsum("ij->ji", NdArrayFactory.array(a, new float[]{1, 2, 3, 4}, 2, 2)).toFloatArray());
        m.put("einsum_elementwise_dot", new float[]{Einsum.einsum("ij,ij->", NdArrayFactory.array(a, new float[]{1, 2, 3, 4}, 2, 2), NdArrayFactory.array(a, new float[]{5, 6, 7, 8}, 2, 2)).flatGetFloat(0)});
        m.put("einsum_general", Einsum.einsum("ik,kj->ij", NdArrayFactory.array(a, new float[]{1, 2, 3, 4}, 2, 2), NdArrayFactory.array(a, new float[]{5, 6, 7, 8}, 2, 2)).toFloatArray());

        // ── Broadcasting ──
        m.put("broadcast_add", Ufunc.add(NdArrayFactory.array(a, new float[]{1, 2, 3}, 1, 3), NdArrayFactory.array(a, new float[]{10, 20}, 2, 1)).toFloatArray());

        // ── Shape ops ──
        m.put("flip", ShapeOps.flip(NdArrayFactory.arange(a, 6)).toFloatArray());
        m.put("roll", ShapeOps.roll(NdArrayFactory.arange(a, 6), 2).toFloatArray());
        m.put("unique", ShapeOps.unique(NdArrayFactory.array(a, new float[]{3, 1, 2, 1, 3, 2})).toFloatArray());
        m.put("diff", ShapeOps.diff(NdArrayFactory.array(a, new float[]{1, 3, 6, 10})).toFloatArray());

        // ── Shape ops (additional) ──
        m.put("reshape", ShapeOps.reshape(NdArrayFactory.arange(a, 12), 3, 4).toFloatArray());
        m.put("transpose", ShapeOps.transpose(ShapeOps.reshape(NdArrayFactory.arange(a, 6), 2, 3)).contiguous().toFloatArray());
        m.put("squeeze", ShapeOps.squeeze(ShapeOps.reshape(NdArrayFactory.arange(a, 3), 1, 3, 1)).toFloatArray());
        m.put("expand_dims", ShapeOps.expandDims(NdArrayFactory.arange(a, 3), 0).toFloatArray());
        m.put("flatten", ShapeOps.flatten(ShapeOps.reshape(NdArrayFactory.arange(a, 6), 2, 3)).toFloatArray());
        m.put("concatenate", ShapeOps.concatenate(new NdArray[]{NdArrayFactory.array(a, new float[]{1, 2}), NdArrayFactory.array(a, new float[]{3, 4})}, 0).toFloatArray());
        m.put("stack", ShapeOps.stack(new NdArray[]{NdArrayFactory.array(a, new float[]{1, 2}), NdArrayFactory.array(a, new float[]{3, 4})}, 0).toFloatArray());
        m.put("hstack", ShapeOps.hstack(NdArrayFactory.array(a, new float[]{1, 2, 3}), NdArrayFactory.array(a, new float[]{4, 5, 6})).toFloatArray());
        m.put("vstack", ShapeOps.vstack(NdArrayFactory.array(a, new float[]{1, 2, 3}), NdArrayFactory.array(a, new float[]{4, 5, 6})).toFloatArray());
        m.put("split_0", ShapeOps.split(NdArrayFactory.arange(a, 9), 3)[0].toFloatArray());
        m.put("tile", ShapeOps.tile(NdArrayFactory.array(a, new float[]{1, 2}), 3).toFloatArray());
        m.put("repeat", ShapeOps.repeat(NdArrayFactory.array(a, new float[]{1, 2, 3}), 2, 0).toFloatArray());
        m.put("fliplr", ShapeOps.fliplr(ShapeOps.reshape(NdArrayFactory.arange(a, 9), 3, 3)).toFloatArray());
        m.put("flipud", ShapeOps.flipud(ShapeOps.reshape(NdArrayFactory.arange(a, 9), 3, 3)).toFloatArray());
        m.put("pad", ShapeOps.pad(NdArrayFactory.array(a, new float[]{1, 2, 3}), 2, 3, 0f).toFloatArray());
        m.put("triu", ShapeOps.triu(ShapeOps.reshape(NdArrayFactory.arange(a, 9), 3, 3)).toFloatArray());
        m.put("tril", ShapeOps.tril(ShapeOps.reshape(NdArrayFactory.arange(a, 9), 3, 3)).toFloatArray());
        m.put("diag_extract", ShapeOps.diag(ShapeOps.reshape(NdArrayFactory.arange(a, 9), 3, 3)).toFloatArray());
        m.put("diag_construct", ShapeOps.diagConstruct(NdArrayFactory.array(a, new float[]{1, 2, 3})).toFloatArray());
        m.put("diagonal", ShapeOps.diagonal(NdArrayFactory.array(a, new float[]{1, 2, 3, 4}, 2, 2)).toFloatArray());
        m.put("trace", new float[]{ShapeOps.trace(NdArrayFactory.array(a, new float[]{1, 2, 3, 4}, 2, 2))});
        m.put("gradient", ShapeOps.gradient(NdArrayFactory.array(a, new float[]{1, 3, 6, 10})).toFloatArray());
        m.put("swapaxes", ShapeOps.swapaxes(ShapeOps.reshape(NdArrayFactory.arange(a, 24), 2, 3, 4), 0, 2).contiguous().toFloatArray());
        m.put("moveaxis", ShapeOps.moveaxis(ShapeOps.reshape(NdArrayFactory.arange(a, 24), 2, 3, 4), 0, 2).contiguous().toFloatArray());
        m.put("meshgrid_x", ShapeOps.meshgrid(NdArrayFactory.array(a, new float[]{1, 2, 3}), NdArrayFactory.array(a, new float[]{4, 5}))[0].toFloatArray());
        m.put("broadcast_to", ShapeOps.broadcastTo(NdArrayFactory.array(a, new float[]{1, 2, 3}), 2, 3).toFloatArray());
        m.put("dstack", ShapeOps.dstack(NdArrayFactory.array(a, new float[]{1, 2}, 2, 1), NdArrayFactory.array(a, new float[]{3, 4}, 2, 1)).toFloatArray());
        m.put("hsplit_0", ShapeOps.hsplit(NdArrayFactory.arange(a, 6), 3)[0].toFloatArray());
        m.put("vsplit_0", ShapeOps.vsplit(ShapeOps.reshape(NdArrayFactory.arange(a, 12), 4, 3), 2)[0].toFloatArray());
        m.put("rot90", ShapeOps.rot90(NdArrayFactory.array(a, new float[]{1, 2, 3, 4}, 2, 2)).toFloatArray());
        m.put("insert", ShapeOps.insert(NdArrayFactory.array(a, new float[]{1, 2, 3, 4}), 2, 99f).toFloatArray());
        m.put("delete", ShapeOps.delete(NdArrayFactory.array(a, new float[]{1, 2, 3, 4}), 1).toFloatArray());
        m.put("append", ShapeOps.append(NdArrayFactory.array(a, new float[]{1, 2, 3}), NdArrayFactory.array(a, new float[]{4, 5, 6})).toFloatArray());

        // ── Indexing ──
        m.put("slice", IndexOps.slice(NdArrayFactory.array(a, new float[]{0, 1, 2, 3, 4, 5}), 1, 4, 1).contiguous().toFloatArray());
        m.put("take", IndexOps.take(NdArrayFactory.array(a, new float[]{10, 20, 30, 40, 50}), new int[]{0, 2, 4}, 0).toFloatArray());
        m.put("boolean_index", IndexOps.booleanIndex(NdArrayFactory.array(a, new float[]{10, 20, 30, 40}), NdArrayFactory.array(a, new float[]{1, 0, 1, 0})).toFloatArray());
        m.put("where", IndexOps.where(NdArrayFactory.array(a, new float[]{1, 0, 1}), NdArrayFactory.array(a, new float[]{10, 20, 30}), NdArrayFactory.array(a, new float[]{-1, -2, -3})).toFloatArray());
        m.put("sort", IndexOps.sort(NdArrayFactory.array(a, new float[]{3, 1, 4, 1, 5, 9})).toFloatArray());
        { int[] ai = IndexOps.argsort(NdArrayFactory.array(a, new float[]{30, 10, 20})).toIntArray(); m.put("argsort", new float[]{ai[0], ai[1], ai[2]}); }
        m.put("searchsorted", new float[]{IndexOps.searchsorted(NdArrayFactory.array(a, new float[]{1, 3, 5, 7}), 4f)});
        { int[] nz = IndexOps.nonzero(NdArrayFactory.array(a, new float[]{0, 1, 0, 3, 0, 5})).toIntArray(); m.put("nonzero", new float[]{nz[0], nz[1], nz[2]}); }
        { NdArray aw = IndexOps.argwhere(NdArrayFactory.array(a, new float[]{0, 1, 0, 3, 0, 5})); int[] awi = aw.toIntArray(); float[] awf = new float[awi.length]; for (int i = 0; i < awi.length; i++) awf[i] = awi[i]; m.put("argwhere", awf); }
        m.put("partition", new float[]{IndexOps.partition(NdArrayFactory.array(a, new float[]{3, 1, 4, 1, 5, 9, 2, 6}), 3).flatGetFloat(3)});
        m.put("fancy_index", IndexOps.fancyIndex(NdArrayFactory.array(a, new float[]{10, 20, 30, 40, 50}), new int[]{0, 2, 4}).toFloatArray());
        { NdArray px = NdArrayFactory.array(a, new float[]{1, 2, 3, 4}); IndexOps.put(px, new int[]{1, 3}, new float[]{99, 88}); m.put("put", px.toFloatArray()); }

        return m;
    }

    private static float[] toF32(NdArray a) {
        double[] d = a.toDoubleArray();
        float[] f = new float[d.length];
        for (int i = 0; i < d.length; i++) f[i] = (float) d[i];
        return f;
    }

    /** Minimal JSON parser for flat {key: [numbers]} structure. */
    private static Map<String, float[]> parseJson(String json) {
        Map<String, float[]> map = new LinkedHashMap<>();
        Pattern keyPattern = Pattern.compile("\"([^\"]+)\"\\s*:\\s*\\[([^\\]]*)]");
        Matcher matcher = keyPattern.matcher(json);
        while (matcher.find()) {
            String key = matcher.group(1);
            if (key.startsWith("_")) continue;
            String[] vals = matcher.group(2).split(",");
            float[] arr = new float[vals.length];
            for (int i = 0; i < vals.length; i++) {
                arr[i] = Float.parseFloat(vals[i].trim());
            }
            map.put(key, arr);
        }
        return map;
    }
}
